apiVersion: v1
kind: Secret
metadata:
  name: genomic-secret
type: Opaque
data:
  db-username: cm9vdA==        # "root"
  db-password: YWRtaW4xMjM=    # "admin123"
  django-secret-key: ZGphbmdvLXNlY3JldC1rZXk=
